# Generated by Django 3.0.5 on 2020-04-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studenttb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('sage', models.IntegerField()),
                ('saddr', models.CharField(max_length=30)),
            ],
        ),
    ]
