# Generated by Django 3.0.3 on 2020-02-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registerinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=15, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('Phone', models.CharField(blank=True, max_length=10, null=True)),
                ('Email', models.EmailField(blank=True, max_length=20, null=True)),
                ('Zip', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
